Remove The Environment Configuration In Favor of Using Default Caches
Removes the manual management of the python configuration and
environment variables in favor of using virtualenvs, and the caching
them appropriately.

The virtualenv bin folder is added to the GITHUB_PATH to make it easily
accessible in the rest of the workflow.

Signed-off-by: Hassan Abouelela <hassan@hassanamr.com>

diff --git a/.github/workflows/test_setup_python.yaml b/.github/workflows/test_setup_python.yaml
--- a/.github/workflows/test_setup_python.yaml
+++ b/.github/workflows/test_setup_python.yaml
@@ -101,6 +101,11 @@ jobs:
 
       - name: Check Cache Content
         run: |
+          if ! command -v mypy; then
+            echo "Expected mypy to be installed in the cache, was not found."
+            exit 1
+          fi
+
           if command -v black; then
             echo "Black was installed in an incorrect context."
             exit 1
